### ISSUE TITLE
`tdd` theme doesn't work with `pdm`

### ISSUE THREAD

**Issue by ljnsn** [DavidVujic/python-polylith#169]
**Describe the bug**
It seems that the `tdd` theme seup is broken with pdm.

**To Reproduce**

```bash
mkdir foopdm && cd foopdm
pdm init -n --backend pdm-backend minimal
# add `pdm-polylith-workspace` hook
touch README.md
pdm add -d polylith-cli
pdm run poly create workspace --name poly
pdm run poly create component --name foo
pdm run poly sync
pdm install
pdm run python -c "from poly import foo"
```

Results in:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'poly'
```

**Expected behavior**
The same behavior as poetry:

```bash
mkdir foopoe && cd foopoe
poetry init
poetry poly create workspace --name poly
poetry poly create component --name foo
poetry poly sync
poetry install
poetry run python -c "from poly import foo"  # no error
```

**Desktop (please complete the following information):**
 - OS: linux
 - Python version: 3.12
 - Poetry version: 1.7.1
 - Pdm version: 2.12.3

**Comment by DavidVujic** [comment]
Thank you for reporting @ljnsn!

I have probably missed out on setting the paths correctly in the generated `pth` file for the tdd theme. I'll have a look!

**Comment by DavidVujic** [comment]
I think this issue is solved now @ljnsn and I have released new versions of the PDM hooks, and also the CLI.

The `tdd` theme needs a sync and pdm install when a new brick has been added. This is the case for Poetry too. 

The reason is because of the dynamic type of paths that is created the tdd theme. This is related to why I came up with the  - for Python - recommended `loose` theme, when learning that I had to add each unique path to my `mypy` configuration with the structure according to how it's done in Clojure.

The hook it is making PDM aware of where the bricks are found. What happens behind the scenes is that the Hook will add a `pth` file to the current virtual environment. 

I haven't found a way to set wildcards to paths, and don't think that is possible.

Other than that, the `tdd` theme should work fine! 😄

**Comment by ljnsn** [comment]
@DavidVujic I can confirm it works now, thanks for the fix! :slightly_smiling_face: 

> when learning that I had to add each unique path to my mypy configuration

What paths did you add? I usually run mypy with `-p <namespace.package>` in monorepos, but it still makes it necessary to list all the different packages, which is definitely not ideal.. I prefer the tests to live in the bricks' directories though, next to the source code, so for now I think there's no way around it.

**Comment by DavidVujic** [comment]
On each PDM build command, there is a `polylith_workspace.pth` file created and handed over to the PDM build process. The paths added are the paths to the bases and components that are defined in the `pyproject.toml` file.

For the `loose` theme, the paths added are simply "/bases" and "/components". This is because the top namespace is directly below that path. And the top namespace is known in beforehand.

For the `tdd` theme, the paths to the top namespace are added such as `/components/my_component_name/src`. The `pth` file is updated each time with the new paths that have been added. I think the same goes for the MyPy config, it needs to know the path - the base/component name is dynamic with the `tdd` theme, so that's why it need to be updated.

Glad to hear that it works! 🎉

**Comment by DavidVujic** [comment]
I wrote a little bit about MyPy in the example repo: https://github.com/DavidVujic/python-polylith-example?tab=readme-ov-file#the-loose-theme
