### ISSUE TITLE
[Guidance] A way to specify SAAS provided dependencies

### ISSUE THREAD

**Issue by Paulskit** [DavidVujic/python-polylith#206]
Hello @DavidVujic,
Thank you for your library, it seems to tick all the boxes for python monorepo I'm trying to build!

I have the following use-case which I'm not sure how to handle properly:
I've got a set of AWS Glue jobs that use the custom python library (built in python-polylith) to unify some common operations. This library has [some dependencies](https://github.com/awslabs/aws-glue-libs) that are available natively only in the execution environment, but is not distributed as a package. 
When project from my bricks and run `poly check` command is run, I get the following error:
`🤔 Cannot locate awsglue in <project_name>` 
I understand that in order to avoid the error I have to specify an implicit dependency, which exists only in the actual execution environment. However, looking at the documentation, I can't really find a way to do this.
Can you please advise what would be the best way to solve this?

**Comment by DavidVujic** [comment]
Hello @Paulskit! I'm happy to hear that you like Polylith 😄 

This is a scenario that I haven't thought of before. I think what would be needed in the `check` command is an `--ignore` option. I think it should be fairly straight forward thing to implement, and I will have a closer look at it.

Meanwhile, if it is a package that can be installed from PyPI, I think a workaround could be to add it as a dev-dependency. 

Otherwise, there is a hack you could do and that is telling the `check` command that `awsglue` is an alias for an existing package already. I know, that's ugly, but it should prevent the `check` command from exiting with an error code, if it's blocking you in a CI environment.

Example `poly check --alias an-existing-dependency=aws_glue`.

**Comment by DavidVujic** [comment]
A follow-up question: how do you install the aws glue library? I had a quick look, but didn't understand it fully. It looked like it can be added as a dependency via github + and then have the OS-specifics also added. If I got that right, would it be added as a Python depencency, from github instead of pypi?

**Comment by Paulskit** [comment]
Hey @DavidVujic. 

I'm using one of the third-party packages of the mentioned repository
```tool
[tool.hatch.envs.default]
dependencies = [
  "awsglue-local-dev==1.0.0",
]
```

Right now, I have applied the workaround in the project as 
![image](https://github.com/DavidVujic/python-polylith/assets/9947675/ed49117f-8e86-4f0d-9425-7fbb0b737ab0)

It did the trick, but can't say I'm happy with it. 
It would be great if implicit dependencies can be somehow put into the pyproject.toml file. Everything in 1 place and a reusable command for all builds out there, just `hatch build -t wheel`

**Comment by DavidVujic** [comment]
Ok, that makes sense!

I got an idea that might solve this: having the poly check command take an optional dependency into account, such as dependencies specified in `tool.hatch.envs.local`. If I understand Hatch correctly, you could pick a specific environment to create in a production environment, and then skip the optionals.

I will give this a try.

**Comment by DavidVujic** [comment]
Just to double check: for production, you aren't installing any python package for this library? Even if there is an `import awsglue`in there, right? I wonder how that works, this scenario I haven't experienced yet.

**Comment by Paulskit** [comment]
Right, for AWS Glue there is a way to provide dependency as a package. 
‘--additional-python-modules s3://aws-glue-native-spark/tests/j4.2/ephem-3.7.7.1-cp37-cp37m-linux_x86_64.whl’
See here: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#addl-python-modules-support

If I had to install it the normal way, obviously my workaround wouldn’t work because of missing package. That’s why I don’t like it.

**Comment by DavidVujic** [comment]
> It did the trick, but can't say I'm happy with it. It would be great if implicit dependencies can be somehow put into the pyproject.toml file. Everything in 1 place and a reusable command for all builds out there, just `hatch build -t wheel`

Will hatch build a proper wheel with that added? I would expect a build failure.

My suggestion would to use the `--alias` feature to workaround this. The option is available for both `poly  check` and `poly libs`. 

Example workaround with the tool as-is today:
`hatch run poly check --alias boto3=awsglue`

I will try out the different possibilities that has been mentioned here: optional dependencies, ignore options or being able to tell the tool about the implicit dependencies.

**Comment by DavidVujic** [comment]
Hello again @Paulskit!

I have published new versions of the Polylith tools (the CLI version is 1.6.0), that will include any optional dependencies added in the projects. I think this could be a solution for your use case.

If you would specify the `awsglue-local-dev` dependency there, it will be included when running the check and libs command. 

Example:
```
[project.optional-dependencies]
local-dev = ["awsglue-local-dev==1.0.0"]
```

Since the "cutoff" to match dependencies is fairly strict, you still would need to use the `--alias` option. But now it will make sense, and you won't need to workaround it as before using some other dependency.

Usage:
```
# check
hatch run poly check --alias awsglue-local-dev=awsglue

# libs
hatch run poly libs --alias awsglue-local-dev=awsglue
```

I will close this issue as completed. Please reopen, or create a new issue if you have any issues! 🙏 

Thank you again for reporting about this thing. By doing that, you have helped me developing a better tool - much appreciated!

**Comment by Paulskit** [comment]
This is fast! Thank you for such a rapid turnaround, I didn't expect it.
