### ISSUE TITLE
Exit codes in libs and check commands

### ISSUE THREAD

**Issue by tomsej** [DavidVujic/python-polylith#58]
**Describe the bug**
If I run `poetry poly libs` or `poetry poly check` and some libraries or bricks are missing, I would expect that last exit code is different to 0. That can help to e.g. CI/CD pipeline decide whether a project is OK or not.

Thanks a lot!

**Comment by DavidVujic** [comment]
The new version  - v1.3.1 - should handle exit codes as you describe for the `poetry poly libs` command.

I have new ideas for the `poly check` command - because it is not really working as expected. Since I developed that command, I have learned a lot about AST and how to parse code (that is actually done in the `poly libs` command).

So, I am planning to rewrite the `poly check` command to be focused on validating the projects having the correct dependencies (just like the `libs` command) and have included all needed components & bases.

After reconsidering this, I no longer think that the `check` command should do any `mypy` actions, that should be done by the developers and from the top-level - to catch typings, typos and errors. The check-command will make sure the actual project-file is up-to-date and not that much more.

And the `poly check` command will be a lot faster too! 😄 

If you have any feedback about these things, please let me know!

**Comment by DavidVujic** [comment]
Hello @tomsej! 

I just released v1.4.0 with a reworked `poetry poly check` command. It no longer runs `MyPy` behind the scenes, but does AST parsing of brick to determine if dependencies are missing.

It's not 100% bullet proof - will miss third-party dependencies if installed globally just as the `libs` command - but runs a lot quicker than before and will also find missing bricks in projects. 

There's still the `poetry check-project` command from the MultiProject plugin, that's doing the `MyPy` checks.

An example:
![poly-check-v2](https://user-images.githubusercontent.com/301286/222952374-5b0796fe-0489-4d82-bd4e-d7388b9a0e55.gif)

**Comment by DavidVujic** [comment]
I think these issues are resolved now 🥳 - so I'll close this one. Please create a new issue if you find things not working as expected! Again, a big thank you for all the feedback! ⭐

**Comment by tomsej** [comment]
Woow looking forward to test it
