### ISSUE TITLE
poly libs is confused by some packages

### ISSUE THREAD

**Issue by bnmnetp** [DavidVujic/python-polylith#83]
**Describe the bug**
When I run poetry poly libs in my repo it complains for several of the projects about `dateutil` and `humps` and `pkg_resources`

Could not locate all libraries in book_server. Caused by missing dependencies?
🤔 dateutil, humps, pkg_resources

**To Reproduce**
run poetry poly libs

**Expected behavior**
The packages mentioned are in the pyproject.toml file so I would not expect there to be a problem

**Desktop (please complete the following information):**
 - OS:
 - Python version: 
 - Poetry version:

**Additional context**

`humps` is provided by the `pyhumps` package
`dateutil` is provided by the `python-dateutil` package

It may be that it is just confused because the package name doesn't match?  Or maybe I'm misunderstanding something?

**Comment by DavidVujic** [comment]
Thank you for reporting this issue!

The `poly libs` command should behave as you expect and only notify about missing libraries. Recently, I did an update to this feature because it tracked libraries in a too simplistic way and missed out on some obvious scenarios.

Now it should identify packages and imports such as "dateutil" and "python-dateutil", even if the names doesn't exactly match. Unless I have introduced a new bug! 🤔 

Are you using the latest version of the polylith plugin? Here's what's been added lately: https://github.com/DavidVujic/python-polylith/releases

To update, you need to remove and then add the plugin again, according to the official Poetry docs.

```
poetry self remove poetry-polylith-plugin

poetry self add poetry-polylith-plugin@latest
```

**Comment by bnmnetp** [comment]
Thanks @DavidVujic That does fix the problem.

I haven't worked much with plugins, I'll have to get used to running
`poetry self show --outdated`

**Comment by DavidVujic** [comment]
Great! I didn't know about the --outdated flag.

**Comment by bnmnetp** [comment]
The remaining mystery is that it lists pkg_resources as missing.  But pkg_resources is part of setuptools... deprecated, I know so I should work on getting rid of it anyway.

**Comment by DavidVujic** [comment]
Ok! Maybe that's the same case as with `__futures__`? I can add both of them to the known standard-library list.
